---
- hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:  
    - name: "Creating temporary scans directory"
      file:
        path: "{{temp_file_storage_path | default('./tmp')}}/"
        state: directory

- hosts: unix_endpoints
  gather_facts: no

  tasks:
    - name: Getting info about scans
      shell: "find {{scanner_output_path}} -maxdepth 1 -type f "
      register: files_to_copy
      changed_when: false

    - name: "Fetch packages from endpoints"
      fetch: 
        src: "{{item}}"
        dest: "{{temp_file_storage_path | default('./tmp')}}/"
        flat: yes
      loop: "{{ files_to_copy.stdout_lines }}"

    - name: Clean up packages on endpoints   
      file:
        state: absent
        path: "{{item}}"
      loop: "{{ files_to_copy.stdout_lines }}"

- hosts: lmtserver
  gather_facts: no
  tasks:
    - name: "Uploading scans to ILTM Server"
      copy:
        src: "{{temp_file_storage_path | default('./tmp')}}/"
        dest: "{{lmt_datasource_path}}/"

- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: "Cleaning scans from Control Node"
      file:
        path: "{{temp_file_storage_path | default('./tmp')}}/"
        state: absent
...